// QuranSurahs.tsx

import React from 'react';

export interface Surah {
  id: number;
  name: string;
  arabic: string;
  ayahs: number;
}

const surahs: Surah[] = [
  { id: 1, name: 'Al-Fatiha', arabic: 'الفاتحة', ayahs: 7 },
  { id: 2, name: 'Al-Baqarah', arabic: 'البقرة', ayahs: 286 },
  { id: 3, name: 'Aal-E-Imran', arabic: 'آل عمران', ayahs: 200 },
  { id: 4, name: 'An-Nisa', arabic: 'النساء', ayahs: 176 },
  { id: 5, name: 'Al-Ma\'idah', arabic: 'المائدة', ayahs: 120 },
  { id: 6, name: 'Al-An\'am', arabic: 'الأنعام', ayahs: 165 },
  { id: 7, name: 'Al-A\'raf', arabic: 'الأعراف', ayahs: 206 },
  { id: 8, name: 'Al-Anfal', arabic: 'الأنفال', ayahs: 75 },
  { id: 9, name: 'At-Tawbah', arabic: 'التوبة', ayahs: 129 },
  { id: 10, name: 'Yunus', arabic: 'يونس', ayahs: 109 },
  { id: 11, name: 'Hud', arabic: 'هود', ayahs: 123 },
  { id: 12, name: 'Yusuf', arabic: 'يوسف', ayahs: 111 },
  { id: 13, name: 'Ar-Ra\'d', arabic: 'الرعد', ayahs: 43 },
  { id: 14, name: 'Ibrahim', arabic: 'إبراهيم', ayahs: 52 },
  { id: 15, name: 'Al-Hijr', arabic: 'الحجر', ayahs: 99 },
  { id: 16, name: 'An-Nahl', arabic: 'النحل', ayahs: 128 },
  { id: 17, name: 'Al-Isra', arabic: 'الإسراء', ayahs: 111 },
  { id: 18, name: 'Al-Kahf', arabic: 'الكهف', ayahs: 110 },
  { id: 19, name: 'Maryam', arabic: 'مريم', ayahs: 98 },
  { id: 20, name: 'Taha', arabic: 'طه', ayahs: 135 },
  { id: 21, name: 'Al-Anbya', arabic: 'الأنبياء', ayahs: 112 },
  { id: 22, name: 'Al-Hajj', arabic: 'الحج', ayahs: 78 },
  { id: 23, name: 'Al-Mu\'minun', arabic: 'المؤمنون', ayahs: 118 },
  { id: 24, name: 'An-Nur', arabic: 'النور', ayahs: 64 },
  { id: 25, name: 'Al-Furqan', arabic: 'الفرقان', ayahs: 77 },
  { id: 26, name: 'Ash-Shu\'ara', arabic: 'الشعراء', ayahs: 227 },
  { id: 27, name: 'An-Naml', arabic: 'النمل', ayahs: 93 },
  { id: 28, name: 'Al-Qasas', arabic: 'القصص', ayahs: 88 },
  { id: 29, name: 'Al-\'Ankabut', arabic: 'العنكبوت', ayahs: 69 },
  { id: 30, name: 'Ar-Rum', arabic: 'الروم', ayahs: 60 },
  { id: 31, name: 'Luqman', arabic: 'لقمان', ayahs: 34 },
  { id: 32, name: 'As-Sajdah', arabic: 'السجدة', ayahs: 30 },
  { id: 33, name: 'Al-Ahzab', arabic: 'الأحزاب', ayahs: 73 },
  { id: 34, name: 'Saba', arabic: 'سبأ', ayahs: 54 },
  { id: 35, name: 'Fatir', arabic: 'فاطر', ayahs: 45 },
  { id: 36, name: 'Ya-Sin', arabic: 'يس', ayahs: 83 },
  { id: 37, name: 'As-Saffat', arabic: 'الصافات', ayahs: 182 },
  { id: 38, name: 'Sad', arabic: 'ص', ayahs: 88 },
  { id: 39, name: 'Az-Zumar', arabic: 'الزمر', ayahs: 75 },
  { id: 40, name: 'Ghafir', arabic: 'غافر', ayahs: 85 },
  { id: 41, name: 'Fussilat', arabic: 'فصلت', ayahs: 54 },
  { id: 42, name: 'Ash-Shura', arabic: 'الشورى', ayahs: 53 },
  { id: 43, name: 'Az-Zukhruf', arabic: 'الزخرف', ayahs: 89 },
  { id: 44, name: 'Ad-Dukhan', arabic: 'الدخان', ayahs: 59 },
  { id: 45, name: 'Al-Jathiyah', arabic: 'الجاثية', ayahs: 37 },
  { id: 46, name: 'Al-Ahqaf', arabic: 'الأحقاف', ayahs: 35 },
  { id: 47, name: 'Muhammad', arabic: 'محمد', ayahs: 38 },
  { id: 48, name: 'Al-Fath', arabic: 'الفتح', ayahs: 29 },
  { id: 49, name: 'Al-Hujurat', arabic: 'الحجرات', ayahs: 18 },
  { id: 50, name: 'Qaf', arabic: 'ق', ayahs: 45 },
  { id: 51, name: 'Adh-Dhariyat', arabic: 'الذاريات', ayahs: 60 },
  { id: 52, name: 'At-Tur', arabic: 'الطور', ayahs: 49 },
  { id: 53, name: 'An-Najm', arabic: 'النجم', ayahs: 62 },
  { id: 54, name: 'Al-Qamar', arabic: 'القمر', ayahs: 55 },
  { id: 55, name: 'Ar-Rahman', arabic: 'الرحمن', ayahs: 78 },
  { id: 56, name: 'Al-Waqi\'ah', arabic: 'الواقعة', ayahs: 96 },
  { id: 57, name: 'Al-Hadid', arabic: 'الحديد', ayahs: 29 },
  { id: 58, name: 'Al-Mujadilah', arabic: 'المجادلة', ayahs: 22 },
  { id: 59, name: 'Al-Hashr', arabic: 'الحشر', ayahs: 24 },
  { id: 60, name: 'Al-Mumtahanah', arabic: 'الممتحنة', ayahs: 13 },
  { id: 61, name: 'As-Saff', arabic: 'الصف', ayahs: 14 },
  { id: 62, name: 'Al-Jumu\'ah', arabic: 'الجمعة', ayahs: 11 },
  { id: 63, name: 'Al-Munafiqun', arabic: 'المنافقون', ayahs: 11 },
  { id: 64, name: 'At-Taghabun', arabic: 'التغابن', ayahs: 18 },
  { id: 65, name: 'At-Talaq', arabic: 'الطلاق', ayahs: 12 },
  { id: 66, name: 'At-Tahrim', arabic: 'التحريم', ayahs: 12 },
  { id: 67, name: 'Al-Mulk', arabic: 'الملك', ayahs: 30 },
  { id: 68, name: 'Al-Qalam', arabic: 'القلم', ayahs: 52 },
  { id: 69, name: 'Al-Haqqah', arabic: 'الحاقة', ayahs: 52 },
  { id: 70, name: 'Al-Ma\'arij', arabic: 'المعارج', ayahs: 44 },
  { id: 71, name: 'Nuh', arabic: 'نوح', ayahs: 28 },
  { id: 72, name: 'Al-Jinn', arabic: 'الجن', ayahs: 28 },
  { id: 73, name: 'Al-Muzzammil', arabic: 'المزمل', ayahs: 20 },
  { id: 74, name: 'Al-Muddaththir', arabic: 'المدثر', ayahs: 56 },
  { id: 75, name: 'Al-Qiyamah', arabic: 'القيامة', ayahs: 40 },
  { id: 76, name: 'Al-Insan', arabic: 'الإنسان', ayahs: 31 },
  { id: 77, name: 'Al-Mursalat', arabic: 'المرسلات', ayahs: 50 },
  { id: 78, name: 'An-Naba', arabic: 'النبأ', ayahs: 40 },
  { id: 79, name: 'An-Nazi\'at', arabic: 'النازعات', ayahs: 46 },
  { id: 80, name: '\'Abasa', arabic: 'عبس', ayahs: 42 },
  { id: 81, name: 'At-Takwir', arabic: 'التكوير', ayahs: 29 },
  { id: 82, name: 'Al-Infitar', arabic: 'الإنفطار', ayahs: 19 },
  { id: 83, name: 'Al-Mutaffifin', arabic: 'المطففين', ayahs: 36 },
  { id: 84, name: 'Al-Inshiqaq', arabic: 'الإنشقاق', ayahs: 25 },
  { id: 85, name: 'Al-Buruj', arabic: 'البروج', ayahs: 22 },
  { id: 86, name: 'At-Tariq', arabic: 'الطارق', ayahs: 17 },
  { id: 87, name: 'Al-A\'la', arabic: 'الأعلى', ayahs: 19 },
  { id: 88, name: 'Al-Ghashiyah', arabic: 'الغاشية', ayahs: 26 },
  { id: 89, name: 'Al-Fajr', arabic: 'الفجر', ayahs: 30 },
  { id: 90, name: 'Al-Balad', arabic: 'البلد', ayahs: 20 },
  { id: 91, name: 'Ash-Shams', arabic: 'الشمس', ayahs: 15 },
  { id: 92, name: 'Al-Layl', arabic: 'الليل', ayahs: 21 },
  { id: 93, name: 'Ad-Duha', arabic: 'الضحى', ayahs: 11 },
  { id: 94, name: 'Ash-Sharh', arabic: 'الشرح', ayahs: 8 },
  { id: 95, name: 'At-Tin', arabic: 'التين', ayahs: 8 },
  { id: 96, name: 'Al-\'Alaq', arabic: 'العلق', ayahs: 19 },
  { id: 97, name: 'Al-Qadr', arabic: 'القدر', ayahs: 5 },
  { id: 98, name: 'Al-Bayyinah', arabic: 'البينة', ayahs: 8 },
  { id: 99, name: 'Az-Zalzalah', arabic: 'الزلزلة', ayahs: 8 },
  { id: 100, name: 'Al-\'Adiyat', arabic: 'العاديات', ayahs: 11 },
  { id: 101, name: 'Al-Qari\'ah', arabic: 'القارعة', ayahs: 11 },
  { id: 102, name: 'At-Takathur', arabic: 'التكاثر', ayahs: 8 },
  { id: 103, name: 'Al-\'Asr', arabic: 'العصر', ayahs: 3 },
  { id: 104, name: 'Al-Humazah', arabic: 'الهمزة', ayahs: 9 },
  { id: 105, name: 'Al-Fil', arabic: 'الفيل', ayahs: 5 },
  { id: 106, name: 'Quraysh', arabic: 'قريش', ayahs: 4 },
  { id: 107, name: 'Al-Ma\'un', arabic: 'الماعون', ayahs: 7 },
  { id: 108, name: 'Al-Kawthar', arabic: 'الكوثر', ayahs: 3 },
  { id: 109, name: 'Al-Kafirun', arabic: 'الكافرون', ayahs: 6 },
  { id: 110, name: 'An-Nasr', arabic: 'النصر', ayahs: 3 },
  { id: 111, name: 'Al-Masad', arabic: 'المسد', ayahs: 5 },
  { id: 112, name: 'Al-Ikhlas', arabic: 'الإخلاص', ayahs: 4 },
  { id: 113, name: 'Al-Falaq', arabic: 'الفلق', ayahs: 5 },
  { id: 114, name: 'An-Nas', arabic: 'الناس', ayahs: 6 },
];

export default surahs;
